services:
  mysql:
    image: mysql:latest
    container_name: cart-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cart-db
    ports:
      - "3309:3306"
    volumes:
      - cart-data:/var/lib/mysql
volumes:
  cart-data: